# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCMC_PSPI_generalizability <- function(X, Y, binary, Z, pi, X_test, pi_test, model, nburn, npost, n_knots, order, ntrees_s = 200L, verbose = FALSE, dart = FALSE, aug = FALSE) {
    .Call(`_PSPI_MCMC_PSPI_generalizability`, X, Y, binary, Z, pi, X_test, pi_test, model, nburn, npost, n_knots, order, ntrees_s, verbose, dart, aug)
}

MCMC_PSPI_fit <- function(X, Y, binary, Z, pi, model, nburn, npost, n_knots, order, ntrees_s = 200L, verbose = FALSE, dart = FALSE, aug = FALSE) {
    .Call(`_PSPI_MCMC_PSPI_fit`, X, Y, binary, Z, pi, model, nburn, npost, n_knots, order, ntrees_s, verbose, dart, aug)
}

MCMC_PSPI_predict <- function(fit, X_pop, pi_pop, verbose = FALSE) {
    .Call(`_PSPI_MCMC_PSPI_predict`, fit, X_pop, pi_pop, verbose)
}

bart_train <- function(X, Y, nburn = 100L, npost = 1000L, verbose = TRUE) {
    .Call(`_PSPI_bart_train`, X, Y, nburn, npost, verbose)
}

